// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhGgRPNO-5wytksnjhq1YU-cTGmdF0DSE',
    appId: '1:205605407348:web:1bd0e5b1c4783f35a69f21',
    messagingSenderId: '205605407348',
    projectId: 'flutter-chat-app-3fa15',
    authDomain: 'flutter-chat-app-3fa15.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3fa15.firebasestorage.app',
    measurementId: 'G-P8EKF04SRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHPkz7YY3wV4ecvtj_CEc8t6yQjY1Cvtg',
    appId: '1:205605407348:android:8ed78e736da4e9cea69f21',
    messagingSenderId: '205605407348',
    projectId: 'flutter-chat-app-3fa15',
    storageBucket: 'flutter-chat-app-3fa15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNKJzTprXsPFeFpnAaUupjYDX3a6x9T0',
    appId: '1:205605407348:ios:8189afbad87bb25da69f21',
    messagingSenderId: '205605407348',
    projectId: 'flutter-chat-app-3fa15',
    storageBucket: 'flutter-chat-app-3fa15.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNKJzTprXsPFeFpnAaUupjYDX3a6x9T0',
    appId: '1:205605407348:ios:8189afbad87bb25da69f21',
    messagingSenderId: '205605407348',
    projectId: 'flutter-chat-app-3fa15',
    storageBucket: 'flutter-chat-app-3fa15.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhGgRPNO-5wytksnjhq1YU-cTGmdF0DSE',
    appId: '1:205605407348:web:683c230c733e66c6a69f21',
    messagingSenderId: '205605407348',
    projectId: 'flutter-chat-app-3fa15',
    authDomain: 'flutter-chat-app-3fa15.firebaseapp.com',
    storageBucket: 'flutter-chat-app-3fa15.firebasestorage.app',
    measurementId: 'G-LLXNXMGESD',
  );

}